### ISSUE TITLE
Process exited with code 1

### ISSUE THREAD

**Issue by LeneFischer** [OpenDroneMap/WebODM#122] opened 2017-03-19 07:31 UTC
Hi
My first question here :-) 
Is this the correct way of asking a question?

Second question:
I start WebODM on Linux and everything run smoothly - Login, Upload images (11 images) and a lot of processing. It all ends with 'Process exited with code 1'

I have tried to look for exception codes - with no luck  - so I ask here.

Any suggestion on what I might have done wrong.
Regards
Lene Fischer

The dialog looks like this long text:

[INFO]    Initializing OpenDroneMap app - Sun Mar 19 07:26:10  2017
[INFO]    Running ODM Load Dataset Cell
[DEBUG]   resize dir: /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/images_resize
[DEBUG]   Loading dataset from: /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/images_resize
[DEBUG]   /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/images_resize
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0017.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0026.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None

[DEBUG]   Loaded DJI_0023.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0022.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0020.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0018.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0021.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0025.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0027.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0024.JPG | camera: dji fc6310 | dimensions: 2400 x 1600 | focal: 8.8 | ccd: None
[INFO]    Found 11 usable images
[INFO]    Running ODM Load Dataset Cell - Finished
[INFO]    Running ODM Resize Cell
[DEBUG]   Resizing dataset to: /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/images_resize
[WARNING] Already resized DJI_0026.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0017.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0023.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0019.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0022.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0018.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0025.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0024.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0027.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0020.JPG | dimensions: 2400 x 1600
[WARNING] Already resized DJI_0021.JPG | dimensions: 2400 x 1600
[INFO]    Resized 11 images
[INFO]    Running ODM Resize Cell - Finished
[INFO]    Running ODM OpenSfM Cell
[WARNING] Found a valid OpenSfM file in: /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/opensfm/reconstruction.json
[WARNING] Found a valid Bundler file in: /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/opensfm/reconstruction.json
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running ODM Meshing Cell
[WARNING] Found a valid ODM Mesh file in: /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/odm_meshing/odm_mesh.ply
[INFO]    Running ODM Meshing Cell - Finished
[INFO]    Running MVS Texturing Cell
[DEBUG]   Writing MVS Textured file in: /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/odm_texturing/odm_textured_model.obj
[DEBUG]   running /code/SuperBuild/install/bin/texrecon /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/opensfm/reconstruction.nvm /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/odm_meshing/odm_mesh.ply /var/www/data/9306309d-ad93-4cf4-9156-f8f8f98249f0/odm_texturing/odm_textured_model -d gmi -o gauss_clamping -t none     
/code/SuperBuild/install/bin/texrecon (built on Mar 18 2017, 00:54:03)
Load and prepare mesh: 
	Could not load mesh: File format not recognized as PLY-model
Traceback (most recent call last):
  File "/code/run.py", line 55, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/mvstex.py", line 109, in process
    '{keepUnseenFaces}'.format(**kwargs))
  File "/code/opendm/system.py", line 28, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1

**Comment by pierotofy** [comment] 2017-03-19 13:36
Hi Lene, yes this is the right place to ask questions.

Since you closed the issue, does that mean that you solved the problem? Or do you still need help? In that case, would it be possible for you to share the dataset (images) you are using?

**Comment by LeneFischer** [comment] 2017-03-20 05:33
Hi Piero,
I closed the issue because I found an answer, that indicated it was RAM that was the issue.
But, haven´t solved the issue yet.

Regards

Lene Fischer
Associate Professor

University of Copenhagen
Department of Geoscience and Natural Resource Management

Forest and Landscape College
Nødebovej 77a
3480
Denmark

TEL +45 40115084
lfi@ign.ku.dk<mailto:lfi@ign.ku.dk>


[cid:image004.gif@01D2A143.DB876510]

[cid:image002.png@01D2A0D7.90033DB0]<@Lene_Fischer> [cid:image003.png@01D2A0D7.90033DB0] <ku-gis.dk/blog>

**Comment by pierotofy** [comment] 2017-03-20 13:16
It really depends on the size of your dataset and what settings you are using. I can run 500+ images datasets on my laptop which has 24 GB ram and 2 cores.

But the error you've experienced might be caused by something other than low memory. Is it possible for you share the dataset with us either publicly or privately?

**Comment by DominikTom** [comment] 2017-03-27 17:57
Hi, 
At first sorry for my english, I
![zrzut ekranu 2017-03-27 o 19 55 33](https://cloud.githubusercontent.com/assets/26257697/24370417/9e680080-1327-11e7-9f73-229627e6d7ad.png)
 have the same problem on WebODM "Process exited with code 1" I work on iMac 256GB SSD, 16GB RAM, 2,7 GHz Intel Core i5 and Intel Iris Pro 1536 MB, Maybe you know where is the problem? I do not have idea :(

".....
2017-03-27 15:40:29,542 Cleaning depthmap for image DJI_0051.JPG
2017-03-27 15:40:30,449 Cleaning depthmap for image DJI_0039.JPG
2017-03-27 15:40:31,331 Cleaning depthmap for image DJI_0072.JPG
2017-03-27 15:40:32,048 Merging depthmaps
Killed
Traceback (most recent call last):
  File "/code/run.py", line 55, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 90, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 28, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 137
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 137"

In agisoft photoscan pro and Pix4d everything looks good with the same photos from Dji Phantom 3 pro
Best Regards 
Dominik

**Comment by pierotofy** [comment] 2017-03-27 18:01
@DominikTom, notice the `Killed` in the console log; it means your machine ran out of memory. Make sure you have assigned your docker container enough RAM: http://stackoverflow.com/a/39720010

**Comment by DominikTom** [comment] 2017-03-27 19:25
Thank you very much! Now It works!
But...Quality is low compared to other programs :( Is it possible to change the quality of orthophotomaps?

**Comment by pierotofy** [comment] 2017-03-27 19:29
We're working to improve the output results. In the meanwhile, if you could open a new issue in the OpenDroneMap repository (https://github.com/OpenDroneMap/OpenDroneMap) with a few screenshots comparing the results you are getting (compared vs other programs) we might be able to provide additional suggestions to improve the output, or at least get a sense of what we need to focus our efforts to.

Thanks!!

**Comment by smathermather** [comment] 2017-03-27 22:16
If you have datasets to share too, those are welcome.

**Comment by LeneFischer** [comment] 2017-03-28 18:00
![dji_0428](https://cloud.githubusercontent.com/assets/9905437/24418886/c7ada9a6-13ed-11e7-9220-c4883286ad77.JPG)
![dji_0429](https://cloud.githubusercontent.com/assets/9905437/24418887/c7b650ba-13ed-11e7-8a30-17c89b226193.JPG)
![dji_0430](https://cloud.githubusercontent.com/assets/9905437/24418890/c7c3a80a-13ed-11e7-9186-07ec362361dd.JPG)
![dji_0431](https://cloud.githubusercontent.com/assets/9905437/24418888/c7bd3a88-13ed-11e7-83d8-1aec82d9a7d9.JPG)
![dji_0432](https://cloud.githubusercontent.com/assets/9905437/24418891/c7c78dbc-13ed-11e7-9a88-16a8d3e43b0c.JPG)
![dji_0433](https://cloud.githubusercontent.com/assets/9905437/24418889/c7bf6182-13ed-11e7-8dc9-344656b8d850.JPG)
![dji_0434](https://cloud.githubusercontent.com/assets/9905437/24418893/c7d401c8-13ed-11e7-88d7-0a98b750adb4.JPG)
![dji_0435](https://cloud.githubusercontent.com/assets/9905437/24418894/c7d56504-13ed-11e7-8761-64d5fefac7f3.JPG)

**Comment by DominikTom** [comment] 2017-03-28 18:03
COMPARE PHOTOSCAN vs PIX4D vs DRONEDEPLOY vs MAPS MADE EASY VS WEBODM
https://drive.google.com/drive/folders/0B7BPgMvhrhZHSjRqM3NKb0dWQlU?usp=sharing

**Comment by pierotofy** [comment] 2017-03-28 18:14
@DominikTom most of the distortion in the WebODM orthophoto is due to the poisson reconstruction mesh. We are working on switching to use a 2.5D mesh (see https://github.com/OpenDroneMap/OpenDroneMap/issues/521) which will increase the orthophoto quality by quite a bit.

**Comment by LeneFischer** [comment] 2017-03-28 19:36
Sorry for opening and closing and opening. Clicked on the wrong button :-O

**Comment by pierotofy** [comment] 2017-03-28 20:28
No worries @LeneFischer 

I just processed the 8 images that you attached, without issues:

![image](https://cloud.githubusercontent.com/assets/1951843/24425781/6109b74a-13d3-11e7-9c90-73cf90416e66.png)

![image](https://cloud.githubusercontent.com/assets/1951843/24425799/71c53cda-13d3-11e7-99d2-b2a133918cd8.png)

How are you running WebODM? Did you set it up using docker?

**Comment by LeneFischer** [comment] 2017-03-28 20:43
This looks great - yes I installed on Ubuntu and Docker as explained on the frontpage.
I will try to install on another computer. Thanks for your help.
Another question: Have you made a docker installation to add to the Live-OSGEO ?

**Comment by pierotofy** [comment] 2017-03-28 20:49
We have not, but this would be a great thing to do. @smathermather would it be too early to ask inclusion of WebODM/OpenDroneMap into Live-OSGEO? https://wiki.osgeo.org/wiki/Live_GIS_Add_Project#What_gets_into_OSGeoLive.3F

**Comment by LeneFischer** [comment] 2017-03-28 20:59
I hope you will - I´m giving a workshop at FOSS4G in Boston in August using WebODM and QGIS. So my question is relevant in this setup :-)

**Comment by dakotabenjamin** [comment] 2017-03-29 15:21
I think that would help us with our workshop as well!

**Comment by smathermather** [comment] 2017-03-29 16:25
What kind of lead time do we need for including ODM in OSGEO live? I'm hoping we can get some of the clustering / scaling + memory and processor use improvements in before we work on getting it into live.

**Comment by LeneFischer** [comment] 2017-03-29 20:46
I have just sent a question to the workshop organizer.

Regards
Lene

**Comment by clarkerz** [comment] 2017-04-13 14:21
So pleased to have finally got ODM and ODMWeb working. I feel a bit embarrassed asking this as have been searching for this all day but I am getting the warning whilst processing images as there is no CCD info in my Phantom 4 Images. What is the impact of that to the end the result and should I manually add it using ---force-ccd but I can't find that using WbeODM. Apologies in advance is this is stupid but I just cannot find it. Thanks for everything you guys are doing with ODM and WEBODM!!...Clarkerz

**Comment by clarkerz** [comment] 2017-04-13 15:24
Fantastic...thanks for that. It's been running for 1 /34 now with 67 photos and appears to be showing the same message now over the last hour... oh well..thought it was too good :)
webapp        | INFO Acquiring lock: Task [Task of 2017-04-13T13:45:56.369Z] (1)
webapp        | INFO Acquiring lock: Task [Task of 2017-04-13T13:45:56.369Z] (1)

**Comment by pierotofy** [comment] 2017-04-30 18:45
Since the original issue seems resolved, I'll close this for now.

**Closed by pierotofy** 2017-04-30 18:45 UTC
Labels: question
