### ISSUE TITLE
Booting worker with pid: 51

### ISSUE THREAD

**Issue by faraztehrani** [OpenDroneMap/WebODM#275] opened 2017-08-29 14:13 UTC
Hello,

I followed the instruction on https://github.com/OpenDroneMap/WebODM/blob/master/README.md to install the program using Docker. At some point during installation it stopped further progress. Here is the last line that it printed on screen: 
Booting worker with pid: 51

It seems it has something to do with Gunicorn.

Do you know how I should proceed?

Thanks,

**Comment by pierotofy** [comment] 2017-08-29 14:25
Looks like a duplicate of #258 

Are you on Windows?

**Comment by faraztehrani** [comment] 2017-08-29 14:30
Yes. The same problem. But, I didn't find a solution over there.

I use Windows 7.

**Comment by pierotofy** [comment] 2017-08-29 14:32
Run `docker-machine ip` from the terminal. Use that value (the IP address, which looks like x.x.x.x) to open a web browser to http://x.x.x.x:8000.

**Comment by faraztehrani** [comment] 2017-08-29 14:35
Great! 

Thanks for your help.

**Closed** 2017-08-29 14:39 UTC
Labels: software fault
