### ISSUE TITLE
Hyphens in filenames break opensfm

### ISSUE THREAD

**Issue by ChipwizBen** [OpenDroneMap/WebODM#648] opened 2019-04-04 08:51 UTC
### How did you install WebODM? (Docker, natively, ...)?

Docker + Native

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

N/A

### What is the problem?

Hyphens in filenames break opensfm
https://community.opendronemap.org/t/fault-with-gcp-list-txt-processing/

### What should be the expected behavior?

Filenames should be POSIX compatible.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

...

**Comment by smathermather** [comment] 2019-04-04 12:35
Agree this is a bug based on what I see in the community post. But if this is an OpenSfM issue, it might be most effective to also submit an issue there: https://github.com/mapillary/OpenSfM/issues

**Comment by pierotofy** [comment] 2019-04-04 14:11
Yep, this should be fixed in OpenSfM. We can track it here as well just for record.

**Comment by ChipwizBen** [comment] 2019-04-04 19:59
Feel free to add to: https://github.com/mapillary/OpenSfM/issues/412

**Comment by pierotofy** [comment] 2019-04-10 15:17
Actually, upon further inspection, I think this is caused by NodeODM's sanitization of filenames. So it's not OpenSfM's fault (the issue should be closed there).

I've pushed a change in NodeODM that allows dashes/hyphens as a temporary workaround,  although a better fix will require sanitizing the GCP list as well. https://github.com/OpenDroneMap/NodeODM/issues/77

**Comment by pierotofy** [comment] 2020-04-02 22:56
This should be fixed. If not, please re-open. :clinking_glasses:

**Closed by pierotofy** 2020-04-02 22:56 UTC
Labels: software fault
