### ISSUE TITLE
Stripes on point cloud, georeferencing is out.

### ISSUE THREAD

**Issue by bcirulis** [OpenDroneMap/WebODM#411] opened 2018-03-21 02:56 UTC
### How did you install WebODM? (Docker, natively, ...)?

Windows 10 Docker CE

### What's your browser and operating system? 

Chrome 65 on Windows 10

### What is the problem?

Generated .ply and .las files are striped.  I think its the same issue as this:

https://github.com/OpenDroneMap/OpenDroneMap/issues/522

### What should be the expected behavior?

correctly referenced point cloud / dsm etc. 

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Using webodm interface on auto-node default settings.  

I have tried multiple different projects but they all end up with the same striped .ply/las files:
 ![ply](https://user-images.githubusercontent.com/31496139/37692809-315af814-2d0f-11e8-9526-11c6b44e52c2.JPG)  

The textured model looks great: 
![textured mode](https://user-images.githubusercontent.com/31496139/37692810-318745ae-2d0f-11e8-8dfd-d58bf496698a.JPG)

georeferencing is out:
![orthophoto](https://user-images.githubusercontent.com/31496139/37692808-312c93a2-2d0f-11e8-908e-99048450d94c.JPG)

dsm is weird:
![dsm](https://user-images.githubusercontent.com/31496139/37692807-3103385e-2d0f-11e8-8bb3-ca3517f6de9c.JPG)

project photos here: https://drive.google.com/file/d/1T8RoKDHCmuNlQobbrrk04cmKXCkFFuku/view?usp=sharing

**Comment by bcirulis** [comment] 2018-03-21 07:25
To add to this, I had it working 3 days ago on a different project, just retried it and the same issue occurs.  Could it be something in the latest update to node-opendronemap?  it was updated 28 hours ago.  
![image](https://user-images.githubusercontent.com/31496139/37698139-3cd2d18c-2d35-11e8-96bc-2956203c8bf6.png)

**Comment by pierotofy** [comment] 2018-03-21 19:27
Perhaps this is a bug. Sounds like a possible regression of PDAL https://github.com/OpenDroneMap/OpenDroneMap/issues/522, but will need to find some time to test to confirm this. In the meanwhile if other users are experiencing the same issue, please chime in.

**Comment by farmdude** [comment] 2018-03-22 17:07
I'm having the same issue...

**Comment by pierotofy** [comment] 2018-03-22 21:40
Thank you @farmdude. I will have some time hopefully this weekend to look into it.

**Comment by bcirulis** [comment] 2018-03-23 03:46
Awesome, thanks!

**Comment by pierotofy** [comment] 2018-03-23 21:40
This is a regression introduced by changes in https://github.com/OpenDroneMap/OpenDroneMap/commit/96be8c43aa165e5ce727dd6262b88bea106b5c88.

Boils down to float datatypes not being large enough to handle the georeferencing offset addition (which truncates precision in both X and Y coordinates).

This affects all datasets.

Example PLY output (odm_georeferenced_model.ply): 

```
property float curvature
end_header
576727 5.1882e+06 162.601 61 69 96 0.025 -0.048 0.999 0
576727 5.1882e+06 162.853 38 52 41 -0.257 0.345 0.903 0
```

Working on a fix, just need to treat PCL pointclouds XYZ as double instead of float.

cc @dakotabenjamin

**Comment by pierotofy** [comment] 2018-03-24 22:24
Well, this is proving trickier that I thought.

Turns out PCL doesn't let you just change from float to double (even by changing the datatype):

Floats are hard coded all over the place when executing a transform:

http://docs.pointclouds.org/1.7.1/transforms_8hpp_source.html (line 83):

```
cloud_out[i].x = static_cast<float> (transform (0, 0) * pt.coeffRef (0) + transform (0, 1) * pt.coeffRef (1) + transform (0, 2) * pt.coeffRef (2) + transform (0, 3));
```

I'll have to manipulate the point cloud without PCL and apply the transform using Eigen directly.

**Comment by pierotofy** [comment] 2018-03-25 14:41
A PR has been opened, when it gets merged this should be resolved.

**Comment by bcirulis** [comment] 2018-03-26 04:05
Great stuff.  Looking forward to trying it out.

**Comment by andesce** [comment] 2018-03-26 11:27
Thank you guys for looking into that bug.  Dakota, I watched your opendronemap presentation in youtube, it was very helpful for me, a beginner trying to understand this open cloud world.

**Comment by bcirulis** [comment] 2018-03-27 03:09
Working amazingly well for me.  Thanks for the fix @pierotofy  

Check out this point cloud of very complex/sparse forest.  Was not expecting it to work this well  
![sg2](https://user-images.githubusercontent.com/31496139/37944717-73dad458-31c8-11e8-9bac-52d07720bfa1.JPG)

**Comment by pierotofy** [comment] 2018-03-30 14:34
This is now resolved. Do an update to pull the latest node-opendronemap image.

**Closed by pierotofy** 2018-03-30 14:34 UTC
Labels: software fault
