### ISSUE TITLE
Potree encountered error when trying to view a 3d textured model

### ISSUE THREAD

**Issue by martinr36** [OpenDroneMap/WebODM#1261] opened 2022-10-27 18:21 UTC
### How did you install WebODM (docker, installer, etc.)?

[Windows Installer]

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[Waterfox G5.0.2 windows 11 22H2]

### What is the problem?

[When trying to view a specific 3D model, when trying to view the textured model it starts to render, then all of a sudden i get the following message:

TypeError: Failed to execute 'bindAttribLocation' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
at Shader.linkProgram (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62614:9)
at Shader.update (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62564:9)
at Renderer.renderOctree (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63529:13)
at Renderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63840:10)
at PotreeRenderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:70348:21)
at Viewer.renderDefault (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89890:14)
at Viewer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89904:11)
at Viewer.loop (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:90028:9)
at onAnimationFrame (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:24409:36)
at onAnimationFrame (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:12858:4)

This is using the windows native version of WebODM on the following laptop:

Chassis & Display Cosmos Series: 15.6" Matte Full HD 144Hz 45% NTSC LED Widescreen (1920x1080)
Processor (CPU) Intel® Core™ i7 Six Core Processor 10750H (2.6GHz, 5GHz Turbo)
Memory (RAM) 16GB Corsair 2666MHz SODIMM DDR4 (2 x 8GB)
Graphics Card NVIDIA® GeForce® GTX 1650 Ti - 4.0GB GDDR5 Video RAM - DirectX® 12.1

While observing task manager, it seems as though only the intergrated graphics is being used (100% utilisation), and no use of the GTX1650 Ti

OS is W11 22H2 (fully up to date)

Other 3D textured models open fine
I've also logged this on [Potree github](https://github.com/potree/potree/issues/1241)]

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

[To replicate this every time, i load the 3D point cloud, select load textured model and after a short time it crashes, I've exported all assets and the resultant zip file is [Here](https://www.dropbox.com/s/t6oasfykoxzirh5/Task-of-2022-10-11T081040003Z-all.zip?dl=0)]

**Comment by Saijin-Naib** [comment] 2022-10-27 18:26
Are you able to test the same model on upstream Firefox (no downstream/mods like Waterfox, PaleMoon, etc), Edge, and/or Chrome?

Also, have you attempted to force Waterfox to use the NVIDIA GPU using the Windows 11 Graphics Options in Settings?

**Comment by martinr36** [comment] 2022-10-27 18:36
Hi Saijin

 

This is actually occurring in the WebODM desktop app, I’ve got the same project on my PC which has a 2070 super installed and its fine on there, if you can explain how I can load it to try in firefox, or Edge I’ll certainly give that a try.

 

Thanks for looking into this

 

Regards

Martin

**Comment by Saijin-Naib** [comment] 2022-10-27 21:25
What version of WebODM for Windows are you using?

My question about the browser is only really relevant if you're using the Docker distribution of WebODM, which you aren't (my bad!).

I can't reproduce the problem on my Linux/docker laptop (Celeron N3450, 4GB RAM, Intel HD 500 iGPU):  
![image](https://user-images.githubusercontent.com/19295950/198400387-f054f035-a070-4a9f-8d3f-617b27a1c3ea.png)

Just about killed my computer to render it though :rofl: 
![image](https://user-images.githubusercontent.com/19295950/198400974-77060097-7732-4a28-a7eb-af7cd231087c.png)

**Comment by martinr36** [comment] 2022-10-27 21:37
The latest version 1.9.16 and the latest build

**Comment by pierotofy** [comment] 2022-10-28 03:47
Does the viewer work with smaller datasets/models? 

Do note that web browser have inherent limitations on how much they can hold in memory; if this is a very large model, we might be hitting the limits of what we can load all at once. 

Related: #383

**Comment by pierotofy** [comment] 2022-10-28 04:37
Possibly also caused by the addition of bump mapping recently, which likely increased the texture memory usage.

**Comment by martinr36** [comment] 2022-10-28 07:41
Hi Piero

 

I first had this happen about a fortnight ago, so pre bump mapping

**Comment by martinr36** [comment] 2022-10-28 07:45
Yes, other models load fine, this isn’t in browser its in the windows app it self

**Comment by martinr36** [comment] 2022-10-28 21:26
@Saijin-Naib , missed your comment about forcing the dedicated graphics, yes I've tried and still crashes

**Comment by Saijin-Naib** [comment] 2022-10-28 22:04
Are both drivers fully current? You can use Intel Driver & Support Assistant to get the latest Intel drivers for your system, and you can use the Nvidia hardware drivers site to filter by your GPU and OS to choose the current drivers.

What comes via Windows Update when you're not on the Insider Program update channels is more or less equivalent to LTS drivers and won't always (almost never) be current.

**Comment by martinr36** [comment] 2022-10-29 11:41
Ok both drivers fully up to date, 1650 Ti set as preferred card globally and for WebODM and still crashing, below are Screenshots of task manager both display 1650 Ti with point cloud and then shortly after the crash

 
![Screenshot 2022-10-29 122713](https://user-images.githubusercontent.com/107694493/198829432-3ec9ed2e-821c-4cb1-813e-c1f22ebd9fbf.png)


![Screenshot 2022-10-29 122952](https://user-images.githubusercontent.com/107694493/198829452-6a8c3c4b-60eb-4f23-a433-803b280f891d.png)

**Comment by martinr36** [comment] 2022-11-03 10:24
Ok, don't know if any of this will help, but yesterday, I downloaded and installed Meshlab, and using that I can open the same model that is causing the crash which seems to be taking slightly longer with build 73, in fact at one point it did open and not crash, but back to crashing, below are some screenshots taken just after meshlab opened the model

![Screenshot_20221102_220742](https://user-images.githubusercontent.com/107694493/199697024-e3fba327-92a4-43b1-8746-d6717cf27737.png)

![Screenshot_20221103_101327](https://user-images.githubusercontent.com/107694493/199697089-bb5394b4-5b3f-4eb5-b6c7-56253a8c4a0a.png)


![Screenshot_20221103_101351](https://user-images.githubusercontent.com/107694493/199697175-d67cb0d4-3289-408d-8337-f95da6fe10a8.png)

**Comment by martinr36** [comment] 2022-11-06 19:24
I guess no further ideas on this then

**Comment by Saijin-Naib** [comment] 2022-11-07 02:54
Have enough room to expand your Windows Pagefile? I'm thinking starting size of 64GB minimum, maybe 96GB. You might simply just be running out of address space (physical RAM + virtual memory [swap/pagefile]).

**Comment by martinr36** [comment] 2022-11-07 11:11
I've set pagefile to 96GB, and that seems to have cured the problem, thanks again to all for your help

**Comment by martinr36** [comment] 2022-11-07 13:00
spoke too soon, opened ok twice, now back to crashing, any logs I can provide then please let me know

**Comment by Saijin-Naib** [comment] 2022-11-07 13:11
Can you set pagefile to 128GB starting and screenshot Task Manager focused on the RAM item when the model is loaded and working?

I still think it's just address space issues for your machine.

**Comment by pierotofy** [comment] 2022-11-07 18:28
Very large models will not load no matter the amount of RAM available on the computer. This is a limitation of  web applications.

**Comment by martinr36** [comment] 2022-11-08 00:06
Ok i set it at 128 and it worked and this is screenshot

![Screenshot_20221107_195551](https://user-images.githubusercontent.com/107694493/200441730-bc9312b7-52d1-48ad-9245-6f9736cc79ad.png)

However, I tried again a bit later and it crashed which i got this screenshot


![Screenshot_20221107_195759](https://user-images.githubusercontent.com/107694493/200441873-f4523269-522a-4caa-afb3-36643ea8d806.png)

**Comment by martinr36** [comment] 2022-11-08 09:50
Ok I've bumped it up to 256GB and it opened, and here's the screenshot

![2022-11-08 (2)](https://user-images.githubusercontent.com/107694493/200529881-d06b93f0-889a-4d03-ab70-a976780b6dad.png)

And then several attempts later  it crashed again

![Screenshot_20221108_094829](https://user-images.githubusercontent.com/107694493/200532332-eca661f5-4fda-45ab-823e-90554451f21a.png)

**Comment by Saijin-Naib** [comment] 2022-11-08 12:08
Are you bumping the starting size and final size of the pagefile that high, or is the starting size smaller? Any delay in allocation can cause an out of memory error, so using a large fixed size pagefile should be much more stable.

**Comment by martinr36** [comment] 2022-11-08 12:11
Both starting and final are the same, see below

![image](https://user-images.githubusercontent.com/107694493/200560522-47882d3c-6420-4113-be0d-1d31de33ef50.png)

**Comment by martinr36** [comment] 2022-11-10 20:58
I guess no further ideas on this then

**Comment by Saijin-Naib** [comment] 2022-11-11 00:27
Not currently, no. I can't replicate the failure on any of my machines with lesser specs. Let's keep this open as new releases come out (and driver releases) to see if we can keep up on it and see if behavior changes.

**Comment by martinr36** [comment] 2022-11-11 01:20
Ok, sounds good me, thanks for the help

**Comment by pierotofy** [comment] 2023-08-21 17:02
This *should* be fixed with the new GLTF support. If the error persists, feel free to reopen! :pray:

**Closed by pierotofy** 2023-08-21 17:02 UTC
Labels: possible software fault

**Comment by martinr36** [comment] 2023-08-23 07:44
This should be fixed with the new GLTF support. If the error persists, feel free to reopen! 🙏

What does this actually, what is GLTF support, and how can I check it
