### ISSUE TITLE
PC cant be exported with chosen projection if no DSM is made

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1242] opened 2022-09-24 13:13 UTC
### How did you install WebODM (docker, installer, etc.)?

Installer

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome and Win 10

### What is the problem?

PointCloud cant be exported with chosen projection if no DSM is made

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

If only PointCloud is the output you cant choose a projection when exporting it.

**Comment by pierotofy** [comment] 2024-09-28 22:37
Can't reproduce (processed without DSM, can export the point cloud).

![image](https://github.com/user-attachments/assets/cb583738-7814-47a8-ac3d-7a4ffea21636)

I'll close this for now. If the issue persists, feel free to re-open with reproduction steps using the latest version :pray:

**Closed by pierotofy** 2024-09-28 22:37 UTC
Labels: possible software fault
