### ISSUE TITLE
Task Completed, but no pointcloud in potree viewer

### ISSUE THREAD

**Issue by HeadLessHUN** [OpenDroneMap/WebODM#791] opened 2020-01-19 20:51 UTC
# What's your browser and operating system?

chrome, installed with docker on archlinux.

### What is the problem?

couldn't load point cloud, in 3D viewer there is no issue in the log from entwine converter. But the dense pointcloud can be downloaded and viewed in other softwares, in potree as well, if i convert it later... (~180 mb laz file)
similar like #738 

### What should be the expected behavior?

Can be viewed by integrated potree viewer

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

i used High resoltion settings with 521 images which are resized to 712px

log from entwine convert and before that
```
Found point cloud: odm_georeferencing/odm_georeferenced_model.laz

Scanning input

1/1: odm_georeferencing/odm_georeferenced_model.laz

Determined SRS from an input file



Entwine Version: 2.0.0
EPT Version: 1.0.0
Input:
	File: odm_georeferencing/odm_georeferenced_model.laz

	Total points: 88,333,376

	Density estimate (per square unit): 908.231

	Threads: [1, 5]

Output:
	Path: entwine_pointcloud/
	Data type: laszip
	Hierarchy type: json
	Sleep count: 2,097,152

	Scale: 0.01

	Offset: (379726, 5265118, 25)

Metadata:
	Bounds: [(379553, 5264977, 12), (379898, 5265260, 38)]
	Cube: [(379552, 5264945, -149), (379900, 5265293, 199)]
	Storing dimensions: [
                X:int32, Y:int32, Z:int32, Intensity:uint16, ReturnNumber:uint8,
                NumberOfReturns:uint8, ScanDirectionFlag:uint8,
                EdgeOfFlightLine:uint8, Classification:uint8, ScanAngleRank:float,
                UserData:uint8, PointSourceId:uint16, GpsTime:double, Red:uint16,
                Green:uint16, Blue:uint16, OriginId:uint32
	]
Build parameters:
	Span: 256
	Resolution 2D: 256 * 256 = 65,536
	Resolution 3D: 256 * 256 * 256 = 16,777,216
	Maximum node size: 65,536
	Minimum node size: 16,384
	Cache size: 64


Adding 0 - odm_georeferencing/odm_georeferenced_model.laz
	Pushes complete - joining...

Done!
```

**Comment by Richardsonmapper** [comment] 2020-02-04 06:47
I am not very experienced at this so please bear with me... 
After using WebODM successfully for the past 6-7 months I recently did an update last week which introduced the Plant Health updates etc and we are now experiencing the same issue as is described above i.e. the 3D viewer in WebODM is now not working and is giving an error tab, see below attachment.

 "Could not load point cloud. This task doesn't seem to have one. Try processing the task again."
![3D Error](https://user-images.githubusercontent.com/60640693/73719458-2d26c180-4728-11ea-80c8-b0c46b7258aa.JPG)

I can however download the textured model .obj file from the WebODM interface and open it in Microsoft 3D viewer but there  appears to be an anomaly in the central portion of the model. i.e. a bulge in the Wetland / Pan which has been flown (See below attachment). Not sure if this is a WebODM processing or image capture issue though. There definitely appears to be a problem with the WebODM 3D viewer interface though. 

![3D viewer downloaded OBJ file](https://user-images.githubusercontent.com/60640693/73720374-74ae4d00-472a-11ea-8e15-42d657b978e3.JPG)

**Comment by pierotofy** [comment] 2020-04-02 23:22
Are the images for this dataset available somewhere so we can try to reproduce this?

**Comment by Richardsonmapper** [comment] 2020-04-05 08:48
Hi Piero, The images are 2.6gb in size zipped, what is the best way to share these with you? RegardsJohn Richardson Sent from Mail for Windows 10 From: Piero ToffaninSent: Friday, 03 April 2020 1:22 amTo: OpenDroneMap/WebODMCc: Richardsonmapper; CommentSubject: Re: [OpenDroneMap/WebODM] Task Completed, but no pointcloud in potree viewer (#791) Are the images for this dataset available somewhere so we can try to reproduce this?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pierotofy** [comment] 2020-04-05 13:15
Probably via Dropbox or Google Drive.

**Comment by Richardsonmapper** [comment] 2020-04-09 10:21
Hi Piero,

Attached below is the Google Drive download link, apologies for the delay
but I have been experiencing some problems with regards to my internet
connection and have been battling to upload them.

https://drive.google.com/file/d/1xhvm1gm67Ol2-Fb6nOTNRtDarMaKRzC_/view?usp=sharing


Regards

**Comment by pierotofy** [comment] 2020-04-09 17:15
Does this problem happen with all datasets or just this one? For example, does this one display a point cloud? https://github.com/pierotofy/drone_dataset_brighton_beach/

What's the disk space available? (Check from the Diagnostic panel)

**Comment by pierotofy** [comment] 2020-04-09 17:21
The dataset itself is OK.

![image](https://user-images.githubusercontent.com/1951843/78922757-115fd480-7a65-11ea-8a61-fc0d87d55857.png)

**Comment by pierotofy** [comment] 2020-04-09 17:22
My guess is that you might have run out of disk space while processing the data?

**Comment by Richardsonmapper** [comment] 2020-04-11 10:03
Hi Piero, I have just checked the disk size - 723gb of space available with 13.5gb of memory available. The above dataset just hangs during processing after leaving it running for 2 days. 

I am busy testing the Brighton Beach dataset at the moment and will revert back to you shortly.

**Comment by Richardsonmapper** [comment] 2020-04-11 10:07
![Brighton Beach](https://user-images.githubusercontent.com/60640693/79041035-ddafb680-7bec-11ea-9f9b-37395844262e.JPG)

Brighton Beach appears to work fine?

**Comment by pierotofy** [comment] 2020-04-11 18:44
Perhaps you don't have sufficient memory to process it. Does it work if you use a processing node from https://webodm.net ?

**Comment by pierotofy** [comment] 2021-02-05 20:22
Closing this, newer versions of the software should have fixed this. Feel free to re-open if the issue persists? :pray:

**Closed by pierotofy** 2021-02-05 20:22 UTC
Labels: possible software fault
